#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS += \
  $(abspath ../../components/homekit)

PROJECT_NAME := homekit-esp32-dht
include $(IDF_PATH)/make/project.mk
