#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
EXTRA_COMPONENT_DIRS += \
    $(abspath ../../components/wolfssl)\
    $(abspath ../../components/homekit)\
    $(abspath ../../components/dht11)

PROJECT_NAME := homekit-esp32-dht
include $(IDF_PATH)/make/project.mk
