#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS += \
    $(abspath ../../components/wolfssl)\
    $(abspath ../../components/homekit)\
    $(abspath ../../components/ws2812)

PROJECT_NAME := homekit-esp32-ledstrip
include $(IDF_PATH)/make/project.mk
