#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS += \
    $(abspath ../../components/wolfssl)\
    $(abspath ../../components/homekit) \
    $(abspath ../../components/ds18b20) 

PROJECT_NAME := homekit-esp32-ds
include $(IDF_PATH)/make/project.mk
