#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS += \
    $(abspath ../../components/wolfssl)\
    $(abspath ../../components/homekit)

PROJECT_NAME := homekit-esp32-switch
include $(IDF_PATH)/make/project.mk
