#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../../../
PROJECT_NAME := homekit-esp
include $(IDF_PATH)/make/project.mk
